version: "2.4"
name: newsroom-e2e-tests
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    mongo:
        image: mongo:6
        ports:
            - "27017:27017"
        tmpfs:
            - /data/db

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
        tmpfs:
            - /usr/share/elasticsearch/data

