web: gunicorn -b 0.0.0.0:$PORT -w 3 newsroom.web.app:app
websocket: python -m newsroom.web.ws
worker: celery -A newsroom.web.worker.celery worker -Q "${SUPERDESK_CELERY_PREFIX}newsroom"
beat: celery -A newsroom.web.worker.celery beat
